"""create initial backend tables

Revision ID: 40ff991fa2a6
Revises: 
Create Date: 2026-07-07 12:07:05.330045

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40ff991fa2a6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('runbook', 'release_checklist', 'incident_postmortem', 'architecture_doc', 'other', name='engineering_document_source_type'), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_engineering_documents_source_type', 'engineering_documents', ['source_type'], unique=False)
    op.create_index('ix_engineering_documents_source_uri', 'engineering_documents', ['source_uri'], unique=False)
    op.create_table('release_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_runs_run_id'), 'release_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_release_runs_status'), 'release_runs', ['status'], unique=False)
    op.create_table('engineering_document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunk_index_non_negative'),
    sa.CheckConstraint('token_count >= 0', name='ck_document_chunk_token_count_non_negative'),
    sa.ForeignKeyConstraint(['document_id'], ['engineering_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_document_id_chunk_index')
    )
    op.create_index('ix_engineering_document_chunks_document_id', 'engineering_document_chunks', ['document_id'], unique=False)
    op.create_index('ix_engineering_document_chunks_document_id_chunk_index', 'engineering_document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_table('release_run_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_run_events_created_at'), 'release_run_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_release_run_events_event_status'), 'release_run_events', ['event_status'], unique=False)
    op.create_index(op.f('ix_release_run_events_event_type'), 'release_run_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_release_run_events_release_run_id'), 'release_run_events', ['release_run_id'], unique=False)
    op.create_index('ix_release_run_events_release_run_id_created_at', 'release_run_events', ['release_run_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_run_events_release_run_id_created_at', table_name='release_run_events')
    op.drop_index(op.f('ix_release_run_events_release_run_id'), table_name='release_run_events')
    op.drop_index(op.f('ix_release_run_events_event_type'), table_name='release_run_events')
    op.drop_index(op.f('ix_release_run_events_event_status'), table_name='release_run_events')
    op.drop_index(op.f('ix_release_run_events_created_at'), table_name='release_run_events')
    op.drop_table('release_run_events')
    op.drop_index('ix_engineering_document_chunks_document_id_chunk_index', table_name='engineering_document_chunks')
    op.drop_index('ix_engineering_document_chunks_document_id', table_name='engineering_document_chunks')
    op.drop_table('engineering_document_chunks')
    op.drop_index(op.f('ix_release_runs_status'), table_name='release_runs')
    op.drop_index(op.f('ix_release_runs_run_id'), table_name='release_runs')
    op.drop_table('release_runs')
    op.drop_index('ix_engineering_documents_source_uri', table_name='engineering_documents')
    op.drop_index('ix_engineering_documents_source_type', table_name='engineering_documents')
    op.drop_table('engineering_documents')
    # ### end Alembic commands ###
