"""Strict planner-argument contracts for AgentFlow tools."""

from __future__ import annotations

import re
from typing import TypeAlias, cast

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.schemas.agent_tool import AgentToolName


class _StrictToolArguments(BaseModel):
    """Base contract that rejects planner-supplied unknown fields."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        frozen=True,
    )


class RunFreshReleaseRiskAnalysisArguments(_StrictToolArguments):
    """Arguments for starting a fresh release-risk analysis."""

    query: str = Field(min_length=5, max_length=500)


class LoadCurrentRiskSnapshotArguments(_StrictToolArguments):
    """Arguments for loading trusted persisted release context."""


class LookupGitHubPullRequestArguments(_StrictToolArguments):
    """Arguments for resolving one persisted GitHub pull request."""

    pull_request_number: int = Field(ge=1)


class LookupJiraIssueArguments(_StrictToolArguments):
    """Arguments for resolving one persisted Jira issue."""

    issue_key: str = Field(min_length=3, max_length=100)

    @field_validator("issue_key")
    @classmethod
    def normalize_issue_key(cls, value: str) -> str:
        """Normalize and validate a Jira issue key."""
        normalized = value.upper()

        if not re.fullmatch(r"[A-Z][A-Z0-9_]*-[1-9][0-9]*", normalized):
            raise ValueError("issue_key must be a valid Jira issue key")

        return normalized


class SearchEngineeringKnowledgeArguments(_StrictToolArguments):
    """Arguments for bounded hybrid engineering-document retrieval."""

    query: str = Field(min_length=1, max_length=1_000)
    top_k: int = Field(default=5, ge=1, le=20)

    @field_validator("query")
    @classmethod
    def reject_blank_query(cls, value: str) -> str:
        """Reject whitespace-only knowledge queries."""
        if not value.strip():
            raise ValueError("query must contain non-whitespace text")

        return value


class LookupReleaseHistoryArguments(_StrictToolArguments):
    """Arguments for loading validated historical release snapshots."""

    limit: int = Field(default=10, ge=1, le=100)


class LookupSimilarReleaseArguments(_StrictToolArguments):
    """Arguments for selecting the most similar historical release."""

    limit: int = Field(default=100, ge=1, le=100)


class LookupApprovalStatusArguments(_StrictToolArguments):
    """Arguments for loading durable approval status."""


class LookupSlackStatusArguments(_StrictToolArguments):
    """Arguments for loading persisted Slack delivery status."""


class SendApprovedSlackAlertArguments(_StrictToolArguments):
    """Arguments for the policy-gated Slack action."""


AgentToolArguments: TypeAlias = (
    RunFreshReleaseRiskAnalysisArguments
    | LoadCurrentRiskSnapshotArguments
    | LookupGitHubPullRequestArguments
    | LookupJiraIssueArguments
    | SearchEngineeringKnowledgeArguments
    | LookupReleaseHistoryArguments
    | LookupSimilarReleaseArguments
    | LookupApprovalStatusArguments
    | LookupSlackStatusArguments
    | SendApprovedSlackAlertArguments
)


_ARGUMENT_MODELS: dict[AgentToolName, type[_StrictToolArguments]] = {
    AgentToolName.RUN_FRESH_RELEASE_RISK_ANALYSIS: (
        RunFreshReleaseRiskAnalysisArguments
    ),
    AgentToolName.LOAD_CURRENT_RISK_SNAPSHOT: (
        LoadCurrentRiskSnapshotArguments
    ),
    AgentToolName.LOOKUP_GITHUB_PULL_REQUEST: (
        LookupGitHubPullRequestArguments
    ),
    AgentToolName.LOOKUP_JIRA_ISSUE: LookupJiraIssueArguments,
    AgentToolName.SEARCH_ENGINEERING_KNOWLEDGE: (
        SearchEngineeringKnowledgeArguments
    ),
    AgentToolName.LOOKUP_RELEASE_HISTORY: (
        LookupReleaseHistoryArguments
    ),
    AgentToolName.LOOKUP_SIMILAR_RELEASE: (
        LookupSimilarReleaseArguments
    ),
    AgentToolName.LOOKUP_APPROVAL_STATUS: (
        LookupApprovalStatusArguments
    ),
    AgentToolName.LOOKUP_SLACK_STATUS: LookupSlackStatusArguments,
    AgentToolName.SEND_APPROVED_SLACK_ALERT: (
        SendApprovedSlackAlertArguments
    ),
}


def validate_agent_tool_arguments(
    *,
    tool_name: AgentToolName,
    arguments: dict[str, object],
) -> AgentToolArguments:
    """Validate untrusted planner arguments for one approved tool.

    Args:
        tool_name: Typed approved tool identifier.
        arguments: Untrusted structured arguments generated by the planner.

    Returns:
        Strict immutable per-tool argument model.

    Raises:
        ValidationError: When required fields are missing, values are invalid,
            or unexpected fields are supplied.
    """
    argument_model = _ARGUMENT_MODELS[tool_name]
    return cast(
        AgentToolArguments,
        argument_model.model_validate(arguments),
    )
